<?php

/**
 * Implements hook_hosting_queues().
 *
 * Returns a list of queues that this module needs to manage.
 */
function hosting_site_probes_hosting_queues() {
  $queues['site_probes'] = array(
    'type' => 'batch',
    'name' => t('Site probes'),
    'description' => t('Probe sites for info.'),
    'frequency' => strtotime("1 hour", 0),
    'min_threads' => 6,
    'max_threads' => 12,
    'threshold' => 100,
    'total_items' => hosting_site_count(),
    'singular' => t('site'),
    'plural' => t('sites'),
  );

  return $queues;
}


/**
 * The main queue callback for the probe queue.
 */
function hosting_site_probes_queue($count) {
  // Otherwise loop over all the hosted sites.
  $sites = hosting_site_probes_get_sites_and_settings();

  foreach ($sites as $site) {
    // TODO: Do the stats aggregation
  }
}

/**
 * Get sites that need to be checked for backup GC.
 *
 * TODO: Make this work
 */
function hosting_site_probes_get_sites_and_settings() {
  $sites = node_load_multiple(array(), array('type'=>'site'));

  return $sites;
}
