<?php

/**
 * Implementation of hook_menu();
 */
function hosting_probes_menu() {
}

/**
 * Returns an array of entities loaded from a site.
 */ 
function hosting_probes_get_entities($site, $entity_type, $limit = NULL, $offset = NULL, $order_by = NULL) {

}

/**
 * Runs a custom SELECT query on a site.
 */
function hosting_probes_select_query($site, $query_options) {

}

/**
 * Runs variable_get on a site.
 */
function hosting_probes_variable_get($site, $variable_name, $default = NULL) {

}

/**
 * Runs variable_set on a site.
 */
function hosting_probes_variable_set($site, $variable_name, $variable_value) {

}

/**
 * Returns a list of enabled modules on a site.
 */
function hosting_probes_module_list($site, $sort = FALSE) {

}

/**
 * Enables module on a site.
 */
function hosting_probes_module_enable($site, $module_list) {

}

/**
 * Disables a module on a site.
 */
function hosting_probes_module_disable($site, $module_list) {

}

/**
 * Helper function. Takes a site node object or nid and returns a site node.
 */
function _hosting_probes_get_site($site) {
  // Load site if it's just a nid
  if (is_numeric($site)) {
    $site = node_load($site);
  }

  if (isset($site->type) && $site->type == 'site') {
    return $site;
  }
  else {
    // The node is not a site.
    return NULL;
  }
}
